/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check Deployment Status
         * @description Check if a project exists and get its URL
         */
        get: operations["getDeployStatus"];
        put?: never;
        /**
         * Deploy Documentation
         * @description Deploy or update documentation. For new projects, an API key will be returned. For updates, the API key must be provided in the Authorization header.
         */
        post: operations["deploy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Projects
         * @description List project(s) associated with the provided API key. Currently returns a single project per API key.
         */
        get: operations["listProjects"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Details
         * @description Get detailed information about a project including file list
         */
        get: operations["getProject"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Permanently delete a project and all its content
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{slug}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Statistics
         * @description Get statistics about a project including file counts and deployment info
         */
        get: operations["getProjectStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/keys/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Regenerate API Key
         * @description Generate a new API key for a project. This invalidates the old key.
         */
        post: operations["regenerateApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        DeployRequest: {
            /**
             * @description Project name from docs.json
             * @example My Documentation
             */
            name: string;
            /**
             * @description Existing project slug (for updates)
             * @example my-docs-abc123
             */
            slug?: string;
            /** @description The docs.json configuration object */
            docsJson: Record<string, never>;
            /** @description Content files to deploy */
            files: {
                /**
                 * @description File path relative to project root
                 * @example index.mdx
                 */
                path: string;
                /** @description File content */
                content: string;
            }[];
        };
        DeployResponse: {
            /** @example true */
            success?: boolean;
            /**
             * @description Project slug
             * @example my-docs-abc123
             */
            slug?: string;
            /**
             * @description Live documentation URL
             * @example https://my-docs-abc123.devdoc.sh
             */
            url?: string;
            /** @description Storage URL */
            blobUrl?: string;
            /** @description Whether this was an update to existing project */
            isUpdate?: boolean;
            /** @description Number of files deployed */
            filesCount?: number;
            /**
             * @description API key (only returned for new projects)
             * @example sk_live_abc123xyz...
             */
            apiKey?: string;
        };
        ProjectListResponse: {
            projects?: components["schemas"]["Project"][];
        };
        Project: {
            /** @example my-docs-abc123 */
            slug?: string;
            /** @example My Documentation */
            name?: string;
            /** @example https://my-docs-abc123.devdoc.sh */
            url?: string;
            /** @example 15 */
            filesCount?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            lastDeployedAt?: string;
        };
        ProjectDetails: {
            slug?: string;
            name?: string;
            url?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            /** Format: date-time */
            lastDeployedAt?: string;
            filesCount?: number;
            /** @description Total size in bytes */
            totalSize?: number;
            files?: {
                path?: string;
                size?: number;
            }[];
            config?: {
                name?: string;
                favicon?: string;
                navigation?: string;
            };
        };
        ProjectStats: {
            slug?: string;
            stats?: {
                totalFiles?: number;
                mdxPages?: number;
                configFiles?: number;
                otherFiles?: number;
                totalSizeBytes?: number;
                totalSizeKB?: number;
            };
            deployment?: {
                /** Format: date-time */
                createdAt?: string;
                /** Format: date-time */
                updatedAt?: string;
                /** Format: date-time */
                lastDeployedAt?: string;
                daysSinceCreation?: number;
            };
            analytics?: {
                /** @example coming soon */
                pageViews?: string;
                /** @example coming soon */
                uniqueVisitors?: string;
            };
        };
        ErrorResponse: {
            /**
             * @description Error message
             * @example API key required
             */
            error?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getDeployStatus: {
        parameters: {
            query: {
                /** @description Project slug */
                slug: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        exists?: boolean;
                        /** @example my-docs-abc123 */
                        slug?: string;
                        /** @example https://my-docs-abc123.devdoc.sh */
                        url?: string;
                    };
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example false */
                        exists?: boolean;
                        slug?: string;
                    };
                };
            };
        };
    };
    deploy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Deployment successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResponse"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API key required for updates */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid API key */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectListResponse"];
                };
            };
            /** @description API key required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid API key */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetails"];
                };
            };
            /** @description API key required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API key does not match this project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /** @example Project my-docs-abc123 has been deleted */
                        message?: string;
                    };
                };
            };
            /** @description API key required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API key does not match this project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProjectStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectStats"];
                };
            };
            /** @description API key required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description API key does not match this project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    regenerateApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Project slug
                     * @example my-docs-abc123
                     */
                    slug: string;
                };
            };
        };
        responses: {
            /** @description New API key generated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                        /**
                         * @description New API key
                         * @example sk_live_abc123xyz...
                         */
                        apiKey?: string;
                    };
                };
            };
            /** @description API key required */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid API key for this project */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
